CREATE TABLE `users` (
	`id` int AUTO_INCREMENT NOT NULL,
	`openId` varchar(64) NOT NULL,
	`name` text,
	`nickname` varchar(50),
	`showFullName` boolean NOT NULL DEFAULT false,
	`email` varchar(320),
	`loginMethod` varchar(64),
	`role` enum('user','admin','superadmin') NOT NULL DEFAULT 'user',
	`gender` enum('male','female','non-binary','prefer-not-to-say'),
	`hasProfilePhoto` boolean NOT NULL DEFAULT false,
	`profilePhotoUrl` text,
	`bio` text,
	`skillRating` float,
	`isRatingVerified` boolean NOT NULL DEFAULT false,
	`isPhotoVerified` boolean NOT NULL DEFAULT false,
	`vibe` enum('competitive','social','both') DEFAULT 'both',
	`pace` enum('fast','rally','both') DEFAULT 'both',
	`playStyle` text,
	`handedness` enum('left','right','ambidextrous') DEFAULT 'right',
	`goals` text,
	`latitude` float,
	`longitude` float,
	`city` varchar(100),
	`region` varchar(100),
	`xp` int NOT NULL DEFAULT 0,
	`level` int NOT NULL DEFAULT 1,
	`currentStreak` int NOT NULL DEFAULT 0,
	`longestStreak` int NOT NULL DEFAULT 0,
	`lastLoginDate` timestamp,
	`isPremium` boolean NOT NULL DEFAULT false,
	`premiumUntil` timestamp,
	`totalGames` int NOT NULL DEFAULT 0,
	`totalMatches` int NOT NULL DEFAULT 0,
	`averageRating` float NOT NULL DEFAULT 0,
	`ageMin` int,
	`ageMax` int,
	`genderPreference` text,
	`skillRatingMin` float,
	`skillRatingMax` float,
	`maxDistance` int NOT NULL DEFAULT 25,
	`isDeleted` boolean NOT NULL DEFAULT false,
	`deletedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`lastSignedIn` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `users_id` PRIMARY KEY(`id`),
	CONSTRAINT `users_openId_unique` UNIQUE(`openId`)
);
